### PR TITLE
Adapt for nREPL 0.7

### LINKED ISSUE #3: Update to work with nrepl 0.7+ changes to transport
In the course of nrepl/nrepl#135. A change was make to `TransportFn` that removed its keywordizing/stringification. This was moved into the bencode transport, where it was really needed.

The same need to be done here. 

@pfeodrippe: what does a response from fastlane look like? What are keywords and what are strings? (e.g. in `:status`?) 

I've been talking to @bbatsov about starting to develop a spec for the raw EDN that nrepl deals with, as there's way more richness than what was possible with bencode, but it also means there's lots of potential surprises about what nrepl messages actually look like..

### PR DESCRIPTION
**Pull request by shen-tian**
Closes #3. This brings in line with the EDN trasnsport that's in nREPL 0.7. The read/write shims are to deal with the fact that `:eval` values are strings internally, whereas we tend to use keywords as input. This does the same job as code that's previously there.

Conversion of status back to strings is no longer needed with the new nREPL test suite. Though this does call for clarification of what should be returned.

I tested this by with checkouts with nrepl's test suite, and it mostly works. The one failing test fails elsewhere too.

We can hold off merging this for a bit? Would be good to let recent changes settle a bit..

### CODE REVIEW

**Comment by bbatsov** [comment]
Yeah, absolutely.

**Comment by shen-tian** [comment]
I've deployed this as `[shen-tian/fastlane "0.2.0-SNAPSHOT"]` in case anyone wants to test anything. I'm checking it against nrepl's test suite here: 

https://circleci.com/gh/shen-tian/workflows/nrepl/tree/fix-fastlane

**Comment by bbatsov** [comment]
So, I guess we should merge this one, right?

**Comment by shen-tian** [comment]
Not yet. Think there's something I needed to check first. Are we releasing nrepl 0.7?

**Comment by bbatsov** [comment]
Probably. There hasn't been a lot of activity lately, so I guess it worth cutting a release just for the sake of the new transport.

**Comment by pfeodrippe** [comment]
Thanks @shen-tian, and sorry for the huge delay... I've missed both this PR and your issue notifications in my email, I'll filter it better there =/.

Are we waiting for nrepl 0.7 release or some other thing, @bbatsov @shen-tian?

**Comment by shen-tian** [comment]
This been on my todo list: I want to ensure this works against 0.7.0-alpha.

The testing is a bit tricky for this, and maybe @pfeodrippe can help. Most of the tests that count are actually in nrepl, which includes fastlane as a test time dependency. It would be easiest if we just wait for 0.7 to come out, then update accordingly. 

To be a bit more proactive, we can do a parallel alpha effort, but I don't know who uses fastlane, and how to ensure it works for the relevant use cases, so am a bit worried about missing something.

Any pointers?

**Comment by pfeodrippe** [comment]
> To be a bit more proactive, we can do a parallel alpha effort, but I don't know who uses fastlane, and how to ensure it works for the relevant use cases, so am a bit worried about missing something.\

Yeah, I don't know either, but I'll be able to take a better look at nrepl tests tomorrow and also try to use it locally with Cider to see if it's all right (I guess it is) o/

Well, if you find a fastlane user or a project which you see fastlane could help, you can @ me

**Comment by shen-tian** [comment]
Just updated to work (and test pasts) with `nrepl 0.7.0-alpha1`. It works AFAIK. I've also repeated the below and it looks fine (i.e. only failure is to do with interrupts)

> I've deployed this as `[shen-tian/fastlane "0.2.0-SNAPSHOT"]` in case anyone wants to test anything. I'm checking it against nrepl's test suite here:
> 
> https://circleci.com/gh/shen-tian/workflows/nrepl/tree/fix-fastlane

I'd be happy to merge this.

**Comment by bbatsov** [comment]
Thanks!

**Comment by pfeodrippe** [comment]
Thank you very much!

p.s. sorry for the unfulfilled promised, I’ve been recovering from a little surgery at last weeks

**Pull request merged**
