### PR TITLE
Add transit transports

### PR DESCRIPTION
**Pull request by pfeodrippe**

### CODE REVIEW

**Comment by pfeodrippe** [comment]
I'm testing it using the local version of branch `transit-transport` at `nrepl/nrepl`

https://github.com/nrepl/nrepl/pull/84

**Comment by bbatsov** [comment]
Seems we only need some content for the README and we're good to go.

**Comment by pfeodrippe** [comment]
Added some README based at `nrepl/bencode`

**Comment by pfeodrippe** [comment]
Is it important to put author metadata for nREPL projects so people can bug me if problems occur, or this is not the main point of it?

**Comment by bbatsov** [comment]
It's not a big deal. I just made you a co-admin of the project. Just make sure you watch it and people will easily find you. :-)

**Comment by pfeodrippe** [comment]
Great! I hope the lord of bugs be nice with us all

**Pull request merged**
